[package]
name = "rust-debug2json"
version = "0.1.0"
edition = "2024"
description = "Converts Rust Debug output to pretty-printed JSON"
license = "SimPL-2.0"
repository = "https://github.com/waldyrious/rust-debug2json"
homepage = "https://waldyrious.github.io/rust-debug2json"

[lib]
crate-type = ["cdylib"] # Compile as a dynamic library for Wasm

[dependencies]
regex = "1.12"
wasm-bindgen = "0.2"
serde_dbgfmt = "0.1.1"
serde_json = { version = "1.0", features = ["preserve_order"] }

[dev-dependencies]
indoc = "2.0"
